version: '3'

services:
  database:
    image: postgres:14.3
    restart: always
    env_file: ./.env
    expose:
      - '5432'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    container_name: ${DOCKER_CONTAINER}
    volumes:
      - ./postgres:/var/lib/postgresql/data
